baseURL = 'https://cameronknox.io/'
locale = 'en-US'
title = "Cameron's Blog"
copyright = "© CameronKnox"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

buildFuture = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
  [markup.highlight]
    style = "monokai"
    codeFences = true
    guessSyntax = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
